### PR TITLE
3stage-priors

### PR DESCRIPTION
**Pull request by steph-w**
Added error messages for when:
1. the 2nd input is larger than the 1st, accounting for the "out of every" number.
2. a non-whole number is entered.
- Created 4 questions
- Edited exp.data_trials

### CODE REVIEW

**Comment by mhtess** [comment]
Thanks Stephanie. This is looking good. A couple of comments:
1. Here you have submitted this whole pull request as one huge commit. It is in general better to make several commits (e.g., initial commit after the fork, then commit when you make some change). In addition, be sure to write informative commit messages. Here is just one place to find advice online for this: http://chris.beams.io/posts/git-commit/
2. You were right that `exp.data_trials` is a little bit messed up. You can see this by writing `exp.data_trials` to the javascript console in Chrome after you've entered some responses (and advanced to the next screen). Notice how `nTimes` is overloaded. This is problematic because we are going to want to be able to decode this later and it's not entirely clear what things mean. Instead of loading `responses` to `nTimes` as is done currently, consider breaking them up into `q1_response` for the text response and `q1_interval` for the drop down menu. Then, at least, we will know what question number they came from.
   Also, `category`, `existence`, and `item`, are coming in as undefineds. Can you see why? (Perhaps some of these are not needed). Also note that the stimulus information is coming from `stims-2.js` 
3. Try to write comments as much as possible, even where I didn't have comments in the original.

**Comment by steph-w** [comment]
Hi Michael,

Sounds good, I'll check these out and get back to you. I can meet regularly
on Tuesdays at 3 pm.
Also, I'm applying to be an intern at Panlex <http://panlex.org/> this
summer and they need the emails of two references.
I would be very thankful if you could be one of my references and put in a
sentence or two about me, however if you're not comfortable I completely
understand!
Let me know if you're okay with this.

Best,
Stephanie


Stephanie Wang
Stanford University | Class of 2017
B.S. Candidate | Symbolic Systems
408.888.0473 | steph17@stanford.edu

**Comment by mhtess** [comment]
This is looking really solid. One change I will recommend is getting rid of the `responses` variable defined in `button`. It's hard to keep track of what is what, and in the error logic and the data recording, it's entirely opaque what is going on. I will recommend something like:

```
      response_1 = {
        ntimes: $("#population_frequency_a").val(),
        out_of: $("#population_comparison_a").val()
      }
```

for each question independently. That way, it'll be easier to see what the code is doing.

**Comment by steph-w** [comment]
I've added separate dictionary objects for each response -- you're right it makes the code a lot easier to understand and debug. However I've kept the responses array because it makes it simpler to check if there is any empty entry, triggering an error if the user doesn't provide input in one of the boxes. Let me know of any further edits I could make.

**Comment by mhtess** [comment]
Nice job. Thanks for this.

**Pull request merged**
